### ISSUE TITLE
Missing the Blocks Validation

### ISSUE THREAD

**Issue by nodeop007** [CoreumFoundation/coreum#912]
Hi,

I am a node operator running a Mainnet Validator node. Until July 11th, it was working fine, missing only 1 or 2 blocks. However, since July 12th, it has been missing 140 to 200 blocks.

Could you please help me understand the reason behind this?

Here are my server specifications:

CPU: 8 vCPU
RAM: 16 GB
Storage: 400 GB

Thank you

**Comment by miladz68** [comment]
Hello nodeop007.
We apologize for the late response. 
This issue have been there from the start but has increased recently (some time after v3 release).
We have started to look into this now, and a lot of the validators including coreum foundation validator (Krypton) have this issue as well. Our guess is that a disk with a better IOPS is needed and we are experimenting on testnet. Could you please share your findings if you have been able to resolve this ? otherwise please share the IOPS of your storage so we can provide further assistance.

**Comment by miladz68** [comment]
Closing this for now. feel free to re-open @nodeop007 .
